### PR TITLE
initial fastlane structures

### PR DESCRIPTION
**Pull request by IzzySoft**
for your MR with F-Droid (https://gitlab.com/fdroid/fdroiddata/-/merge_requests/7294) :wink:

### CODE REVIEW

**Comment by IzzySoft** [comment]
@deviant-studio any chance this will be processed? I'm about cleaning up my Github account before this year's end and drop "old forks" I don't plan to maintain – and once I drop the fork of your app, this PR will go "stale" as the source is gone.

**Comment by mykola-dev** [comment]
> 
> 
> @deviant-studio any chance this will be processed? I'm about cleaning up my Github account before this year's end and drop "old forks" I don't plan to maintain – and once I drop the fork of your app, this PR will go "stale" as the source is gone.

Hi @IzzySoft 
Unfortunately i have no time to handle this.
The Fdroid publishing flow became too complicated for me.  I was hoping to publish the app in 2 mins or so but spent a week on it during a vacation. So eventually i gave up few months ago :(
Thanks for your help anyway!

**Comment by IzzySoft** [comment]
Ugh, I don't see where you're stuck? Here it's just pushing the "Merge" button – and with the next release, that part of the review at F-Droid is solved. Then you'd just need to remove summary+description there and add the two lines for `CurrentVersion` and `CurrentVersionCode` at the end. The few (optional) additions are copy-pasted in a minute (I could even do that after it has been merged then, as they are rather optional).

Or is there something I missed, and you are talking about other complications I don't see?

However: currently, your app is [listed in my repo](https://apt.izzysoft.de/fdroid/index/apk/ds.photosight). I'd be grateful if you could merge this for the sake of that then – so you can maintain description etc. and maybe even include screenshots (be welcome using my [Fastlane Cheat Sheet](https://gitlab.com/snippets/1895688) for orientation), and my updater would fetch any changes along with new versions. I'd feel summary+description are the essential parts, all else is at your convenience. As you're the one who knows when things changed and descriptions/screenshots should be updated, this would take care they're not forgotten at my end (or F-Droid's, should we still manage to get it merged there).

Thanks a lot!

**Comment by mykola-dev** [comment]
merged. thanks for helping with this. i'll back to this when have more time

**Comment by IzzySoft** [comment]
Thanks a lot! Feel free to ping me should you need help with this topic. I've enabled it now for your app in my repo (to check summary/description on new releases and pull it when changed). Should you add screenshots etc please let me know to enable them as well.

**Comment by IzzySoft** [comment]
I just wonder why you removed it again? Intentionally, or by accident?

**Comment by mykola-dev** [comment]
hey @IzzySoft 
the integration process is too complex. i don't have time to manage it. and i remember when last time i made a pull request it took several months to review it. so doesn't worth the effort.

**Comment by IzzySoft** [comment]
I see. May I then ask you that, should the description or the screenshots change, you drop me a note with the new description and screenshots to update the listing? While this will mean additional work on my end, it's the only way left to keep it up-to-date if simply placing the files into a directory structure (which is all that's needed for the Fastlane structure) is no option for you. Updates to the Fastlane structure would be picked up automatically with the next release, btw.

**Comment by mykola-dev** [comment]
You can use readme.md as listing description.
btw what is it for? is it for f-droid integration? is it alive? i think the app was never published there. but i may be wrong.

**Comment by IzzySoft** [comment]
> You can use readme.md as listing description.

I cannot monitor it for changes and apply them manually, sorry. There is [a listing up](https://apt.izzysoft.de/fdroid/index/apk/ds.photosight) currently (which is what the Fastlane data here was based upon). If provided in a structured way (here: Fastlane), it can be kept up-to-date automatically. If not, it has to be done manually. With almost 900 apps in the repo, I could not keep up with that this way.

> is it alive?

since 2020-11-28, yes :smiley:

> i think the app was never published there.

Not at F-Droid.org, no. But other than Play, F-Droid isn't a single walled garden basket. There are [many repositories](https://android.izzysoft.de/articles/named/list-of-fdroid-repos) out there you can use with [many F-Droid clients](https://android.izzysoft.de/applists/category/named/apps_markets#group_1181). F-Droid's own is the biggest (with around 4k apps in the main one), mine is the second-largest repository (with close to 900 apps).

So apologies if I wasn't clear enough about this. Fastlane would mean a central place where *you* can maintain description, screenshots etc. the way *you* want your app to be presented. That structure is supported by different places, like F-Droid or my repo. Using the Fastlane binaries, you could even push to Play and Apple, maybe even more.

**Comment by mykola-dev** [comment]
thanks for the clarification. well, actually i can revert the fastlane dir back if it helps with publishing. i'll do it probably after migration to the jetpack compose

**Comment by IzzySoft** [comment]
That'd be great, thanks! And remember you can always ask if you need clarification/help. Let me give you some guiding links:

* My [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) to check what options exist, what goes where etc.
* My [Fastlane Wiki page](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Fastlane) with formatting hints for `full_description.txt` (e.g. what's allowed, what's recommended to use)

I tried to keep both as short and informative as possible. If you strip the comments, each of them easily fits on a single screen. If something's unclear, just ask (might even help improve those 2 documents :wink:)

**Pull request merged**
